//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated by a tool.
//     Runtime Version:4.0.30319.42000
//
//     Changes to this file may cause incorrect behavior and will be lost if
//     the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace WpfApp.ServerASMX {
    using System.Data;
    
    
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    [System.ServiceModel.ServiceContractAttribute(Namespace="http://serverASMX.org/", ConfigurationName="ServerASMX.ServerSoap")]
    public interface ServerSoap {
        
        [System.ServiceModel.OperationContractAttribute(Action="http://serverASMX.org/GetUsers", ReplyAction="*")]
        [System.ServiceModel.XmlSerializerFormatAttribute(SupportFaults=true)]
        System.Data.DataTable GetUsers();
        
        [System.ServiceModel.OperationContractAttribute(Action="http://serverASMX.org/GetUsers", ReplyAction="*")]
        System.Threading.Tasks.Task<System.Data.DataTable> GetUsersAsync();
        
        [System.ServiceModel.OperationContractAttribute(Action="http://serverASMX.org/GetRoles", ReplyAction="*")]
        [System.ServiceModel.XmlSerializerFormatAttribute(SupportFaults=true)]
        System.Data.DataTable GetRoles();
        
        [System.ServiceModel.OperationContractAttribute(Action="http://serverASMX.org/GetRoles", ReplyAction="*")]
        System.Threading.Tasks.Task<System.Data.DataTable> GetRolesAsync();
    }
    
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    public interface ServerSoapChannel : WpfApp.ServerASMX.ServerSoap, System.ServiceModel.IClientChannel {
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    public partial class ServerSoapClient : System.ServiceModel.ClientBase<WpfApp.ServerASMX.ServerSoap>, WpfApp.ServerASMX.ServerSoap {
        
        public ServerSoapClient() {
        }
        
        public ServerSoapClient(string endpointConfigurationName) : 
                base(endpointConfigurationName) {
        }
        
        public ServerSoapClient(string endpointConfigurationName, string remoteAddress) : 
                base(endpointConfigurationName, remoteAddress) {
        }
        
        public ServerSoapClient(string endpointConfigurationName, System.ServiceModel.EndpointAddress remoteAddress) : 
                base(endpointConfigurationName, remoteAddress) {
        }
        
        public ServerSoapClient(System.ServiceModel.Channels.Binding binding, System.ServiceModel.EndpointAddress remoteAddress) : 
                base(binding, remoteAddress) {
        }
        
        public System.Data.DataTable GetUsers() {
            return base.Channel.GetUsers();
        }
        
        public System.Threading.Tasks.Task<System.Data.DataTable> GetUsersAsync() {
            return base.Channel.GetUsersAsync();
        }
        
        public System.Data.DataTable GetRoles() {
            return base.Channel.GetRoles();
        }
        
        public System.Threading.Tasks.Task<System.Data.DataTable> GetRolesAsync() {
            return base.Channel.GetRolesAsync();
        }
    }
}
