//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated by a tool.
//     Runtime Version:4.0.30319.42000
//
//     Changes to this file may cause incorrect behavior and will be lost if
//     the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace WpfApp.Server {
    using System.Runtime.Serialization;
    using System;
    
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.Runtime.Serialization", "4.0.0.0")]
    [System.Runtime.Serialization.DataContractAttribute(Name="CompositeType", Namespace="http://schemas.datacontract.org/2004/07/ServerWCF")]
    [System.SerializableAttribute()]
    public partial class CompositeType : object, System.Runtime.Serialization.IExtensibleDataObject, System.ComponentModel.INotifyPropertyChanged {
        
        [System.NonSerializedAttribute()]
        private System.Runtime.Serialization.ExtensionDataObject extensionDataField;
        
        [System.Runtime.Serialization.OptionalFieldAttribute()]
        private bool BoolValueField;
        
        [System.Runtime.Serialization.OptionalFieldAttribute()]
        private string StringValueField;
        
        [global::System.ComponentModel.BrowsableAttribute(false)]
        public System.Runtime.Serialization.ExtensionDataObject ExtensionData {
            get {
                return this.extensionDataField;
            }
            set {
                this.extensionDataField = value;
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public bool BoolValue {
            get {
                return this.BoolValueField;
            }
            set {
                if ((this.BoolValueField.Equals(value) != true)) {
                    this.BoolValueField = value;
                    this.RaisePropertyChanged("BoolValue");
                }
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public string StringValue {
            get {
                return this.StringValueField;
            }
            set {
                if ((object.ReferenceEquals(this.StringValueField, value) != true)) {
                    this.StringValueField = value;
                    this.RaisePropertyChanged("StringValue");
                }
            }
        }
        
        public event System.ComponentModel.PropertyChangedEventHandler PropertyChanged;
        
        protected void RaisePropertyChanged(string propertyName) {
            System.ComponentModel.PropertyChangedEventHandler propertyChanged = this.PropertyChanged;
            if ((propertyChanged != null)) {
                propertyChanged(this, new System.ComponentModel.PropertyChangedEventArgs(propertyName));
            }
        }
    }
    
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    [System.ServiceModel.ServiceContractAttribute(ConfigurationName="Server.IService")]
    public interface IService {
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/IService/GetData", ReplyAction="http://tempuri.org/IService/GetDataResponse")]
        string GetData(int value);
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/IService/GetData", ReplyAction="http://tempuri.org/IService/GetDataResponse")]
        System.Threading.Tasks.Task<string> GetDataAsync(int value);
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/IService/GetDataUsingDataContract", ReplyAction="http://tempuri.org/IService/GetDataUsingDataContractResponse")]
        WpfApp.Server.CompositeType GetDataUsingDataContract(WpfApp.Server.CompositeType composite);
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/IService/GetDataUsingDataContract", ReplyAction="http://tempuri.org/IService/GetDataUsingDataContractResponse")]
        System.Threading.Tasks.Task<WpfApp.Server.CompositeType> GetDataUsingDataContractAsync(WpfApp.Server.CompositeType composite);
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/IService/GetRoles", ReplyAction="http://tempuri.org/IService/GetRolesResponse")]
        System.Data.DataTable GetRoles();
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/IService/GetRoles", ReplyAction="http://tempuri.org/IService/GetRolesResponse")]
        System.Threading.Tasks.Task<System.Data.DataTable> GetRolesAsync();
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/IService/GetUsers", ReplyAction="http://tempuri.org/IService/GetUsersResponse")]
        System.Data.DataTable GetUsers();
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/IService/GetUsers", ReplyAction="http://tempuri.org/IService/GetUsersResponse")]
        System.Threading.Tasks.Task<System.Data.DataTable> GetUsersAsync();
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/IService/AddRoles", ReplyAction="http://tempuri.org/IService/AddRolesResponse")]
        void AddRoles(string[] rolesArray);
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/IService/AddRoles", ReplyAction="http://tempuri.org/IService/AddRolesResponse")]
        System.Threading.Tasks.Task AddRolesAsync(string[] rolesArray);
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/IService/AddUsers", ReplyAction="http://tempuri.org/IService/AddUsersResponse")]
        void AddUsers(System.Data.DataTable dtUsers);
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/IService/AddUsers", ReplyAction="http://tempuri.org/IService/AddUsersResponse")]
        System.Threading.Tasks.Task AddUsersAsync(System.Data.DataTable dtUsers);
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/IService/UpdateUsers", ReplyAction="http://tempuri.org/IService/UpdateUsersResponse")]
        void UpdateUsers(System.Data.DataTable dtUsers);
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/IService/UpdateUsers", ReplyAction="http://tempuri.org/IService/UpdateUsersResponse")]
        System.Threading.Tasks.Task UpdateUsersAsync(System.Data.DataTable dtUsers);
    }
    
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    public interface IServiceChannel : WpfApp.Server.IService, System.ServiceModel.IClientChannel {
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    public partial class ServiceClient : System.ServiceModel.ClientBase<WpfApp.Server.IService>, WpfApp.Server.IService {
        
        public ServiceClient() {
        }
        
        public ServiceClient(string endpointConfigurationName) : 
                base(endpointConfigurationName) {
        }
        
        public ServiceClient(string endpointConfigurationName, string remoteAddress) : 
                base(endpointConfigurationName, remoteAddress) {
        }
        
        public ServiceClient(string endpointConfigurationName, System.ServiceModel.EndpointAddress remoteAddress) : 
                base(endpointConfigurationName, remoteAddress) {
        }
        
        public ServiceClient(System.ServiceModel.Channels.Binding binding, System.ServiceModel.EndpointAddress remoteAddress) : 
                base(binding, remoteAddress) {
        }
        
        public string GetData(int value) {
            return base.Channel.GetData(value);
        }
        
        public System.Threading.Tasks.Task<string> GetDataAsync(int value) {
            return base.Channel.GetDataAsync(value);
        }
        
        public WpfApp.Server.CompositeType GetDataUsingDataContract(WpfApp.Server.CompositeType composite) {
            return base.Channel.GetDataUsingDataContract(composite);
        }
        
        public System.Threading.Tasks.Task<WpfApp.Server.CompositeType> GetDataUsingDataContractAsync(WpfApp.Server.CompositeType composite) {
            return base.Channel.GetDataUsingDataContractAsync(composite);
        }
        
        public System.Data.DataTable GetRoles() {
            return base.Channel.GetRoles();
        }
        
        public System.Threading.Tasks.Task<System.Data.DataTable> GetRolesAsync() {
            return base.Channel.GetRolesAsync();
        }
        
        public System.Data.DataTable GetUsers() {
            return base.Channel.GetUsers();
        }
        
        public System.Threading.Tasks.Task<System.Data.DataTable> GetUsersAsync() {
            return base.Channel.GetUsersAsync();
        }
        
        public void AddRoles(string[] rolesArray) {
            base.Channel.AddRoles(rolesArray);
        }
        
        public System.Threading.Tasks.Task AddRolesAsync(string[] rolesArray) {
            return base.Channel.AddRolesAsync(rolesArray);
        }
        
        public void AddUsers(System.Data.DataTable dtUsers) {
            base.Channel.AddUsers(dtUsers);
        }
        
        public System.Threading.Tasks.Task AddUsersAsync(System.Data.DataTable dtUsers) {
            return base.Channel.AddUsersAsync(dtUsers);
        }
        
        public void UpdateUsers(System.Data.DataTable dtUsers) {
            base.Channel.UpdateUsers(dtUsers);
        }
        
        public System.Threading.Tasks.Task UpdateUsersAsync(System.Data.DataTable dtUsers) {
            return base.Channel.UpdateUsersAsync(dtUsers);
        }
    }
}
